import Head from 'next/head'
import { Container } from 'react-bootstrap';

const Home = () => {
  return (
    <div>
      <Head>
        <title># Optimizely Next.js (Client Side Rendering) test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>Hello World!</h1>
      </Container>
    </div>
  )
}

export default Home;
